Repository gdg-hongik-univ/gdsc-server, pull requests merged in 2024-10, with the labels that each got.

#796 feat: 수강생 명단 페이지 대시보드 조회 API 추가
  src/main/java/com/gdschongik/gdsc/domain/study/api/MentorStudyController.java
  src/main/java/com/gdschongik/gdsc/domain/study/application/MentorStudyService.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/AssignmentHistoryCustomRepository.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/AssignmentHistoryCustomRepositoryImpl.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/AssignmentHistoryQueryMethod.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/AssignmentHistoryRepository.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/AttendanceCustomRepository.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/AttendanceCustomRepositoryImpl.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/StudyAchievementCustomRepository.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/StudyAchievementCustomRepositoryImpl.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/StudyAchievementRepository.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/StudyHistoryRepository.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/vo/Curriculum.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/AssignmentSubmissionStatusResponse.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/AttendanceStatusResponse.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/StudyStudentCurriculumResponse.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/StudyStudentResponse.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/StudyTodoResponse.java
Labels: ✨ feature

#798 feat: 스터디 수료 내역 조회 API
  src/main/java/com/gdschongik/gdsc/domain/study/api/StudentStudyHistoryController.java
  src/main/java/com/gdschongik/gdsc/domain/study/application/StudentStudyHistoryService.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/StudyAchievementRepository.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/StudentMyCompleteStudyResponse.java
Labels: ✨ feature, ⚓ Domain: Study

#806 feat: 스터디원 엑셀 다운로드 API 추가
  src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
  src/main/java/com/gdschongik/gdsc/domain/study/api/MentorStudyController.java
  src/main/java/com/gdschongik/gdsc/domain/study/application/MentorStudyService.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/StudyHistoryRepository.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/StudyTodoResponse.java
  src/main/java/com/gdschongik/gdsc/global/common/constant/WorkbookConstant.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
  src/main/java/com/gdschongik/gdsc/global/util/ExcelUtil.java
Labels: ✨ feature

#807 feat: 수강생 명단 조회 API와 엑셀에 수료 여부 필드 추가
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/StudyStudentResponse.java
  src/main/java/com/gdschongik/gdsc/global/common/constant/WorkbookConstant.java
  src/main/java/com/gdschongik/gdsc/global/util/ExcelUtil.java
Labels: ✨ feature

#812 refactor: StudyTodoResponse 이름 변경
  src/main/java/com/gdschongik/gdsc/domain/study/api/StudentStudyDetailController.java
  src/main/java/com/gdschongik/gdsc/domain/study/application/MentorStudyService.java
  src/main/java/com/gdschongik/gdsc/domain/study/application/StudentStudyDetailService.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/StudyStudentResponse.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/StudyTaskResponse.java
  src/main/java/com/gdschongik/gdsc/global/util/ExcelUtil.java
Labels: ♻️ refactor
