Repository gdg-hongik-univ/gdsc-server, pull requests merged in 2024-11, with the labels that each got.

#813 feat: StudyAchievement가 BaseEntity 확장하도록 수정
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyAchievement.java
Labels: ✨ feature

#814 refactor: enum 및 변수명 `canceled`로 통일
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyStatus.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/vo/Assignment.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/vo/Curriculum.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/AssignmentSubmissionStatusResponse.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/AssignmentSubmittableDto.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/AttendanceStatusResponse.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/StudyStudentResponse.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/StudyTaskResponse.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
  src/test/java/com/gdschongik/gdsc/domain/study/application/MentorStudyDetailServiceTest.java
  src/test/java/com/gdschongik/gdsc/domain/study/domain/StudyDetailTest.java
Labels: ♻️ refactor

#809 feat: 스터디 통계 조회 API 추가
  src/main/java/com/gdschongik/gdsc/domain/study/api/MentorStudyDetailController.java
  src/main/java/com/gdschongik/gdsc/domain/study/application/MentorStudyDetailService.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/AssignmentHistoryRepository.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/AttendanceRepository.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyHistory.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/StudyStatisticsResponse.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/StudyWeekStatisticsResponse.java
Labels: ✨ feature, ⚓ Domain: Study

#820 refactor: 온보딩 bevy 관련 로직 및 테스트 제거
  src/main/java/com/gdschongik/gdsc/domain/member/api/OnboardingMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/AssociateRequirement.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/MemberFullDto.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/AdminMemberResponse.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
  src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java
  src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberTest.java
  src/test/java/com/gdschongik/gdsc/domain/membership/domain/MembershipTest.java
  src/test/java/com/gdschongik/gdsc/domain/membership/domain/MembershipValidatorTest.java
  src/test/java/com/gdschongik/gdsc/domain/study/domain/StudyTest.java
  src/test/java/com/gdschongik/gdsc/helper/FixtureHelper.java
  src/test/java/com/gdschongik/gdsc/helper/IntegrationTest.java
Labels: ♻️ refactor
