Repository gdg-hongik-univ/gdsc-server, pull requests merged in 2024-06, with the labels that each got.

#340 refactor: 멤버 엔티티 승인 함수 준회원 승급으로 변경
  src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/api/OnboardingMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/request/BasicMemberInfoRequest.java
  src/test/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberServiceTest.java
  src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java
  src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberTest.java
  src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
Labels: ♻️ refactor, ⚓ Domain: Admin

#345 feat: Recruitment 생성 API 구현
  src/main/java/com/gdschongik/gdsc/domain/common/model/SemesterType.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/api/AdminRecruitmentController.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentService.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/dao/RecruitmentRepository.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/Recruitment.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/vo/Period.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/dto/request/RecruitmentCreateRequest.java
  src/main/java/com/gdschongik/gdsc/global/common/constant/RegexConstant.java
  src/main/java/com/gdschongik/gdsc/global/common/constant/TemporalConstant.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
  src/test/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentServiceTest.java
Labels: ✨ feature, ⚓ Domain: Recruitment

#353 feat: 멤버 기본 회원 정보 조회 API 구현
  src/main/java/com/gdschongik/gdsc/domain/member/api/OnboardingMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberBasicInfoResponse.java
Labels: ✨ feature, ⚓ Domain: Onboarding

#361 refactor: 멤버십에 리쿠르팅을 외래키로 추가
  src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
  src/main/java/com/gdschongik/gdsc/domain/membership/dao/MembershipRepository.java
  src/main/java/com/gdschongik/gdsc/domain/membership/domain/Membership.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
  src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
  src/test/java/com/gdschongik/gdsc/domain/membership/domain/MembershipTest.java
Labels: ♻️ refactor

#349 refactor : 멤버 도메인 준회원 승급 조건 추가 - 기본 정보 작성
  src/main/java/com/gdschongik/gdsc/domain/member/application/handler/MemberAssociateEventHandler.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/listener/MemberAssociateEventListener.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberQueryMethod.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/MemberAssociateEvent.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Requirement.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
  src/test/java/com/gdschongik/gdsc/domain/member/application/MemberIntegrationTest.java
  src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java
  src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberTest.java
  src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
Labels: ✅ test, ♻️ refactor, ⚓ Domain: ETC

#383 feat: 리쿠르팅에 회비와 차수 추가
  src/main/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentService.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/dao/RecruitmentRepository.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/Recruitment.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/RoundType.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/dto/request/RecruitmentCreateRequest.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
  src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
  src/test/java/com/gdschongik/gdsc/domain/membership/domain/MembershipTest.java
  src/test/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentServiceTest.java
  src/test/java/com/gdschongik/gdsc/domain/recruitment/domain/RecruitmentTest.java
  src/test/java/com/gdschongik/gdsc/global/common/constant/RecruitmentConstant.java
Labels: ✨ feature, ⚓ Domain: Recruitment

#352 feat: Recruitment 조회 API 구현
  src/main/java/com/gdschongik/gdsc/domain/recruitment/api/AdminRecruitmentController.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentService.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/application/RecruitmentService.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/dao/RecruitmentCustomRepository.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/dao/RecruitmentCustomRepositoryImpl.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/dao/RecruitmentRepository.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/vo/AcademicYearSemesterKey.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/dto/response/AdminRecruitmentResponse.java
  src/main/resources/application-datasource.yml
  src/test/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentServiceTest.java
  src/test/java/com/gdschongik/gdsc/global/common/constant/RecruitmentConstant.java
Labels: ⚓ Domain: Recruitment

#387 feat: 리쿠르팅 수정 API 구현
  src/main/java/com/gdschongik/gdsc/domain/common/model/BaseSemesterEntity.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/api/AdminRecruitmentController.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentService.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/Recruitment.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/vo/AcademicYearSemesterKey.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/dto/request/RecruitmentCreateUpdateRequest.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
  src/test/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentServiceTest.java
  src/test/java/com/gdschongik/gdsc/global/common/constant/RecruitmentConstant.java
Labels: ✨ feature, ⚓ Domain: Recruitment

#381 feat: 기존 학교 이메일 인증 API 기능(동작 방식) 재구성
  src/main/java/com/gdschongik/gdsc/domain/email/api/OnboardingUnivEmailController.java
  src/main/java/com/gdschongik/gdsc/domain/email/application/UnivEmailVerificationLinkSendService.java
  src/main/java/com/gdschongik/gdsc/domain/email/application/UnivEmailVerificationService.java
  src/main/java/com/gdschongik/gdsc/domain/email/dto/request/EmailVerificationTokenDto.java
  src/main/java/com/gdschongik/gdsc/domain/email/dto/request/UnivEmailVerificationRequest.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/AssociateRequirement.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
  src/main/java/com/gdschongik/gdsc/global/common/constant/EmailConstant.java
  src/main/java/com/gdschongik/gdsc/global/common/constant/JwtConstant.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
  src/main/java/com/gdschongik/gdsc/global/util/JwtUtil.java
  src/main/java/com/gdschongik/gdsc/global/util/email/EmailVerificationTokenUtil.java
  src/main/java/com/gdschongik/gdsc/global/util/email/VerificationCodeGenerator.java
  src/main/java/com/gdschongik/gdsc/global/util/email/VerificationLinkUtil.java
  src/main/resources/application-security.yml
Labels: ⚓ Domain: Membership

#394 feat: 정회원 시트 추가
  src/main/java/com/gdschongik/gdsc/global/common/constant/WorkbookConstant.java
  src/main/java/com/gdschongik/gdsc/global/util/ExcelUtil.java
Labels: ⚓ Domain: Admin

#395 refactor: 사용하지 않는 QueryDSL 로직 제거
  src/main/java/com/gdschongik/gdsc/domain/email/dao/UnivEmailVerificationRepository.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberQueryMethod.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberRepository.java
Labels: ♻️ refactor

#393 feat: 정회원 일괄 강등 API 구현
  src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberDemoteRequest.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentService.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/Recruitment.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
  src/test/java/com/gdschongik/gdsc/domain/member/application/AdminMemberServiceTest.java
Labels: ✨ feature

#403 fix: PhoneFormatter의 null 처리
  src/main/java/com/gdschongik/gdsc/global/util/formatter/PhoneFormatter.java
Labels: 🐛 bug/error

#401 rename: `VERIFIED`를 `SATISFIED`로 변경
  src/main/java/com/gdschongik/gdsc/domain/common/model/RequirementStatus.java
  src/main/java/com/gdschongik/gdsc/domain/discord/application/CommonDiscordService.java
  src/main/java/com/gdschongik/gdsc/domain/discord/application/handler/DiscordIdBatchCommandHandler.java
  src/main/java/com/gdschongik/gdsc/domain/email/application/UnivEmailVerificationLinkSendService.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/AssociateRequirement.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
  src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
  src/main/java/com/gdschongik/gdsc/domain/membership/domain/Membership.java
  src/main/java/com/gdschongik/gdsc/domain/membership/domain/RegularRequirement.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
  src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberTest.java
  src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
Labels: ♻️ refactor

#405 feat: 프록시 URL 추가
  src/main/java/com/gdschongik/gdsc/global/common/constant/UrlConstant.java
  src/main/java/com/gdschongik/gdsc/global/config/WebSecurityConfig.java
Labels: ✨ feature

#406 refactor: `this`를 필요한 경우에만 사용하도록 수정
  src/main/java/com/gdschongik/gdsc/domain/common/vo/Money.java
  src/main/java/com/gdschongik/gdsc/domain/coupon/domain/IssuedCoupon.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/AssociateRequirement.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
  src/main/java/com/gdschongik/gdsc/domain/membership/domain/Membership.java
  src/main/java/com/gdschongik/gdsc/domain/membership/domain/RegularRequirement.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/Recruitment.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/vo/Period.java
  src/main/java/com/gdschongik/gdsc/global/security/CustomOAuth2User.java
Labels: ♻️ refactor

#411 refactor: 대기중인 회원 조회 API 제거
  src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
Labels: ♻️ refactor, ⚓ Domain: Admin

#412 feat: 스터디 도메인 테이블 추가
  src/main/java/com/gdschongik/gdsc/domain/study/domain/Difficulty.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/Study.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyDetail.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyHistory.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyNotification.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyType.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/vo/Assignment.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/vo/Session.java
Labels: ✨ feature

#414 test: 테스트 템플릿 위치 변경
  src/test/java/com/gdschongik/gdsc/domain/coupon/application/CouponServiceTest.java
  src/test/java/com/gdschongik/gdsc/domain/member/application/AdminMemberServiceTest.java
  src/test/java/com/gdschongik/gdsc/domain/member/application/MemberIntegrationTest.java
  src/test/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberServiceTest.java
  src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java
  src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
  src/test/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentServiceTest.java
  src/test/java/com/gdschongik/gdsc/helper/DatabaseCleaner.java
  src/test/java/com/gdschongik/gdsc/helper/IntegrationTest.java
  src/test/java/com/gdschongik/gdsc/helper/RepositoryTest.java
Labels: ✅ test

#413 refactor: 디스코드 유저네임 활용 로직을 id 활용으로 변경
  src/main/java/com/gdschongik/gdsc/domain/discord/application/handler/DelegateMemberDiscordEventHandler.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/MemberRegularEvent.java
  src/main/java/com/gdschongik/gdsc/domain/membership/domain/Membership.java
  src/main/java/com/gdschongik/gdsc/global/util/DiscordUtil.java
Labels: ♻️ refactor

#419 refactor: 스터디 세션 엔티티 필드명 수정
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyDetail.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/vo/Session.java
Labels: ♻️ refactor

#420 feat: BaseTimeEntity에 생성자와 수정자 추가
  src/main/java/com/gdschongik/gdsc/domain/common/model/BaseEntity.java
  src/main/java/com/gdschongik/gdsc/domain/common/model/BaseSemesterEntity.java
  src/main/java/com/gdschongik/gdsc/domain/coupon/domain/Coupon.java
  src/main/java/com/gdschongik/gdsc/domain/coupon/domain/IssuedCoupon.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyDetail.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyNotification.java
  src/main/java/com/gdschongik/gdsc/global/config/AuditorAwareImpl.java
  src/main/java/com/gdschongik/gdsc/global/config/JpaConfig.java
  src/test/java/com/gdschongik/gdsc/domain/member/application/MemberIntegrationTest.java
Labels: ✨ feature
