Repository gdg-hongik-univ/gdsc-server, pull requests merged in 2024-02, with the labels that each got.

#38 feat: 멤버 탈퇴 api 구현
  src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/MemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepository.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberRepository.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/MemberStatus.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
  src/main/java/com/gdschongik/gdsc/global/security/CustomUserService.java
Labels: ✨ feature

#43 feat: requirement 도메인 구현
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
  src/main/java/com/gdschongik/gdsc/domain/requirement/domain/Requirement.java
  src/main/java/com/gdschongik/gdsc/domain/requirement/domain/RequirementStatus.java
Labels: ✨ feature

#39 feat: 어드민 멤버 정보 수정 api 구현
  src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/MemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/MemberStatus.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberUpdateRequest.java
  src/main/java/com/gdschongik/gdsc/global/common/constant/RegexConstant.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorResponse.java
  src/main/java/com/gdschongik/gdsc/global/exception/GlobalExceptionHandler.java
  src/test/java/com/gdschongik/gdsc/domain/member/application/MemberServiceTest.java
Labels: ✨ feature

#54 feat: 헬스체크 API를 위한 actuator 설정
  build.gradle
  src/main/java/com/gdschongik/gdsc/global/config/WebSecurityConfig.java
  src/main/resources/application-actuator.yml
  src/main/resources/application.yml
Labels: ✨ feature

#46 docs: admin member api 문서화
  src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberQueryRequest.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberUpdateRequest.java
Labels: 📝 documentation

#56 chore: 도커허브에 올라간 이미지를 재배포하는 워크플로우 추가
  .github/workflows/develop_deploy.yml
Labels: ⚙️ chore

#44 feat: 어드민 대기중인 멤버 조회 api 구현
  src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/MemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberRepository.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Requirement.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/RequirementStatus.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberPendingFindAllResponse.java
Labels: ✨ feature

#59 fix: 스웨거 Basic Auth가 작동하지 않는 문제 해결
  src/main/java/com/gdschongik/gdsc/global/config/WebSecurityConfig.java
Labels: 🐛 bug/error

#65 refactor: 멤버 도메인이 dto에 의존하지 않도록 개선
  src/main/java/com/gdschongik/gdsc/domain/member/application/MemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
Labels: ♻️ refactor

#64 feat: 소셜 로그인 시 랜딩할 페이지 결정에 사용할 헤더 추가
  src/main/java/com/gdschongik/gdsc/global/common/constant/SecurityConstant.java
  src/main/java/com/gdschongik/gdsc/global/security/CustomOAuth2User.java
  src/main/java/com/gdschongik/gdsc/global/security/CustomSuccessHandler.java
  src/main/java/com/gdschongik/gdsc/global/security/LandingStatus.java
Labels: ✨ feature

#63 feat: 어드민 멤버 가입신청 승인하기 api 구현
  src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/MemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepository.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberGrantRequest.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberGrantResponse.java
Labels: ✨ feature

#68 refactor: 멤버 가입 신청 request dto 수정
  src/main/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberSignupRequest.java
Labels: ♻️ refactor

#70 feat: 어드민 승인 가능 멤버 조회 기능
  src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepository.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
Labels: ✨ feature

#71 feat: 온보딩 멤버 정보 수정하기
  src/main/java/com/gdschongik/gdsc/domain/member/api/OnboardingMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/request/OnboardingMemberUpdateRequest.java
Labels: ✨ feature

#72 feat: 온보딩 멤버 정보 조회 기능
  src/main/java/com/gdschongik/gdsc/domain/member/api/OnboardingMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberInfoResponse.java
Labels: ✨ feature

#86 refactor: 온보딩 회원 정보 조회에 입금자명 추가
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberInfoResponse.java
Labels: ♻️ refactor

#85 refactor: 탈퇴 회원을 조회 api에서 제외
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepository.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberRepository.java
Labels: ♻️ refactor

#88 refactor: 조회 api 정렬 조건 추가
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
Labels: ♻️ refactor

#77 feat: 재학생 인증 여부 확인 api 구현
  src/main/java/com/gdschongik/gdsc/domain/member/api/OnboardingMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberUnivStatusResponse.java
Labels: ✨ feature

#89 feat: 회비 미납 회원 목록 조회 api 구현
  src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepository.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
Labels: ✨ feature

#93 feat: 회비 납부 처리 api 구현
  src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Requirement.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberPaymentRequest.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberPaymentResponse.java
Labels: ✨ feature

#74 refactor: 전화번호 format에 대한 처리
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberQueryRequest.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberSignupRequest.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberUpdateRequest.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberFindAllResponse.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberInfoResponse.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberPendingFindAllResponse.java
Labels: ♻️ refactor

#97 refactor: 회비 납부 정보를 전체, 미납, 납부로 나누어 볼 수 있도록 수정
  src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberPaymentFindAllResponse.java
Labels: ♻️ refactor

#104 fix: dto의 phone에서 발생 가능한 NPE 제거
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberFindAllResponse.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberPendingFindAllResponse.java
Labels: 🐛 bug/error

#106 refactor: 회원 승인 응답에 이름을 담도록 수정
  src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepository.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberGrantResponse.java
  src/main/java/com/gdschongik/gdsc/global/config/QuerydslConfig.java
Labels: ♻️ refactor, ⚓ Domain: Admin

#108 fix: 승인 과정에서 발생하는 npe 처리
  src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepository.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
Labels: 🐛 bug/error, ⚓ Domain: Admin

#112 feat: 학과를 enum으로 관리
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Department.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberQueryRequest.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberSignupRequest.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberUpdateRequest.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberFindAllResponse.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberInfoResponse.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberPendingFindAllResponse.java
  src/main/java/com/gdschongik/gdsc/global/common/constant/RegexConstant.java
  src/test/java/com/gdschongik/gdsc/domain/member/application/AdminMemberServiceTest.java
Labels: ✨ feature

#114 feat: 회원 목록 조회 api에 검색 파라미터 추가
  src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepository.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
Labels: ✨ feature, ⚓ Domain: Admin

#121 refactor: 회원 정보 조회 API에 가입 상태 추가
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberInfoResponse.java
Labels: ♻️ refactor, ⚓ Domain: Onboarding

#135 fix: DTO의 학과 정보 로직 NPE 제거
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberFindAllResponse.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberPendingFindAllResponse.java
Labels: 🐛 bug/error, ⚓ Domain: Admin

#139 feat: 학과 검색 API 추가
  src/main/java/com/gdschongik/gdsc/domain/member/api/CommonMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/CommonMemberService.java
Labels: ✨ feature, ⚓ Domain: Onboarding, ⚓ Domain: Admin

#162 fix: 도커 컴포즈 실행 명령 수정
  .github/workflows/production_build_deploy.yml
Labels: 🐛 bug/error

#165 feat: 승인 가능 회원 조회 API에 검색 기능 추가
  src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepository.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
Labels: ✨ feature, ⚓ Domain: Admin

#167 chore: PROD 환경 JPA 설정 변경
  src/main/resources/application-prod.yml
Labels: ⚙️ chore

#173 fix: 쿠키 SameSite 설정 변경
  src/main/java/com/gdschongik/gdsc/global/util/CookieUtil.java
Labels: 🐛 bug/error

#176 fix: 메일 인증 API security 설정 수정
  src/main/java/com/gdschongik/gdsc/global/config/WebSecurityConfig.java
Labels: 🐛 bug/error

#184 chore: 이미지 태그가 자동 생성되는 것을 막고 직접 버전을 주입
  .github/workflows/production_build_deploy.yml
Labels: ⚙️ chore

#208 chore: 클라이언트 어드민 URL에 대한 CORS 설정
  src/main/java/com/gdschongik/gdsc/global/common/constant/UrlConstant.java
  src/main/java/com/gdschongik/gdsc/global/config/WebSecurityConfig.java
  src/main/java/com/gdschongik/gdsc/global/security/CustomSuccessHandler.java
  src/main/java/com/gdschongik/gdsc/global/util/email/VerificationLinkUtil.java
Labels: ⚙️ chore

#203 refactor: 검색 조건에서 학과를 문자열로 받도록 수정
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Department.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberQueryRequest.java
Labels: ♻️ refactor, ⚓ Domain: Admin

#204 refactor: 학과 정보를 코드와 이름 모두 포함하도록 수정
  src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/AdminMemberResponse.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberFindAllResponse.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberPaymentFindAllResponse.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberPendingFindAllResponse.java
Labels: ♻️ refactor, ⚓ Domain: Admin
