Repository gdg-hongik-univ/gdsc-server, pull requests merged in 2024-07, with the labels that each got.

#422 refactor: 스터디 세션 및 과제 상태 enum값 추가
  src/main/java/com/gdschongik/gdsc/domain/study/domain/Study.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyDetail.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyStatus.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/vo/Assignment.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/vo/Session.java
Labels: ♻️ refactor

#460 fix: 진행중인 모집회차가 없을 경우 `CustomException` 발생하도록 수정
  src/main/java/com/gdschongik/gdsc/domain/recruitment/application/OnboardingRecruitmentService.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
Labels: 🐛 bug/error

#458 feat: 모집회차 조회 API 추가
  src/main/java/com/gdschongik/gdsc/domain/recruitment/api/AdminRecruitmentController.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentService.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/dto/response/AdminRecruitmentResponse.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/dto/response/AdminRecruitmentRoundResponse.java
  src/main/java/com/gdschongik/gdsc/global/util/formatter/SemesterFormatter.java
Labels: ✨ feature

#452 refactor: 리쿠르팅 생성 API 수정
  src/main/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentService.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/dao/RecruitmentRepository.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/RecruitmentValidator.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/dto/request/RecruitmentCreateRequest.java
  src/test/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentServiceTest.java
  src/test/java/com/gdschongik/gdsc/domain/recruitment/domain/RecruitmentValidatorTest.java
Labels: ♻️ refactor

#464 refactor: 멤버십 가입 신청 접수 API 수정
  src/main/java/com/gdschongik/gdsc/domain/membership/api/MembershipController.java
  src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
  src/main/java/com/gdschongik/gdsc/domain/membership/dao/MembershipCustomRepository.java
  src/main/java/com/gdschongik/gdsc/domain/membership/dao/MembershipCustomRepositoryImpl.java
  src/main/java/com/gdschongik/gdsc/domain/membership/dao/MembershipRepository.java
  src/main/java/com/gdschongik/gdsc/domain/membership/domain/Membership.java
  src/main/java/com/gdschongik/gdsc/domain/membership/domain/MembershipValidator.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
  src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
  src/test/java/com/gdschongik/gdsc/domain/membership/domain/MembershipTest.java
  src/test/java/com/gdschongik/gdsc/domain/membership/domain/MembershipValidatorTest.java
Labels: ♻️ refactor, ⚓ Domain: Membership

#437 feat: 쿠폰지급용 정회원+준회원 조회 API 추가
  src/main/java/com/gdschongik/gdsc/domain/member/api/AdminMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepository.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberCustomRepositoryImpl.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberQueryMethod.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberQueryOption.java
  src/test/java/com/gdschongik/gdsc/domain/member/dao/MemberRepositoryTest.java
Labels: ✨ feature

#431 feat: 스터디 개설하기 API 추가
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
  src/main/java/com/gdschongik/gdsc/domain/study/api/AdminStudyController.java
  src/main/java/com/gdschongik/gdsc/domain/study/application/AdminStudyService.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/StudyDetailRepository.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/StudyRepository.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/Study.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyDetail.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/vo/Assignment.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/vo/Session.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/request/StudyCreateRequest.java
  src/main/java/com/gdschongik/gdsc/domain/study/factory/StudyDomainFactory.java
  src/main/java/com/gdschongik/gdsc/global/common/constant/RegexConstant.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
  src/test/java/com/gdschongik/gdsc/domain/study/domain/StudyTest.java
  src/test/java/com/gdschongik/gdsc/global/common/constant/StudyConstant.java
Labels: ✨ feature

#474 refactor: 모집회차 수정하기 API 수정
  src/main/java/com/gdschongik/gdsc/domain/recruitment/api/AdminRecruitmentController.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentService.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/RecruitmentRound.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/RecruitmentRoundValidator.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/dto/request/RecruitmentRoundCreateRequest.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/dto/request/RecruitmentRoundCreateUpdateRequest.java
  src/test/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentServiceTest.java
  src/test/java/com/gdschongik/gdsc/domain/recruitment/domain/RecruitmentRoundValidatorTest.java
Labels: ♻️ refactor, ⚓ Domain: Recruitment

#480 feat: 리쿠르팅에 회비 이름 추가
  src/main/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentService.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/Recruitment.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/dto/request/RecruitmentCreateRequest.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/dto/response/AdminRecruitmentResponse.java
  src/test/java/com/gdschongik/gdsc/domain/membership/domain/MembershipTest.java
  src/test/java/com/gdschongik/gdsc/domain/membership/domain/MembershipValidatorTest.java
  src/test/java/com/gdschongik/gdsc/domain/order/domain/OrderValidatorTest.java
  src/test/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentServiceTest.java
  src/test/java/com/gdschongik/gdsc/domain/recruitment/domain/RecruitmentRoundValidatorTest.java
  src/test/java/com/gdschongik/gdsc/domain/recruitment/domain/RecruitmentTest.java
  src/test/java/com/gdschongik/gdsc/global/common/constant/RecruitmentConstant.java
  src/test/java/com/gdschongik/gdsc/helper/IntegrationTest.java
Labels: ✨ feature

#488 refactor: 메일 발송 요청 로직에 도메인 서비스 적용
  src/main/java/com/gdschongik/gdsc/domain/email/application/UnivEmailVerificationLinkSendService.java
  src/main/java/com/gdschongik/gdsc/domain/email/domain/HongikUnivEmailValidator.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberRepository.java
  src/main/java/com/gdschongik/gdsc/global/util/email/HongikUnivEmailValidator.java
  src/test/java/com/gdschongik/gdsc/domain/email/domain/HongikUnivEmailValidatorTest.java
Labels: ♻️ refactor

#487 feat: 임시 토큰 발급 API 추가
  .gitignore
  src/main/java/com/gdschongik/gdsc/domain/member/api/TestMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/request/MemberTokenRequest.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberTokenResponse.java
  src/main/java/com/gdschongik/gdsc/global/common/constant/EnvironmentConstant.java
  src/main/java/com/gdschongik/gdsc/global/config/WebSecurityConfig.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
  src/main/java/com/gdschongik/gdsc/global/util/EnvironmentUtil.java
Labels: ✨ feature

#493 refactor: Formatter 로직 수정 및 Deprecated 기능 제거
  src/main/java/com/gdschongik/gdsc/domain/common/model/SemesterType.java
  src/main/java/com/gdschongik/gdsc/domain/discord/application/OnboardingDiscordService.java
  src/main/java/com/gdschongik/gdsc/domain/discord/application/handler/JoinCommandHandler.java
  src/main/java/com/gdschongik/gdsc/domain/discord/application/listener/JoinCommandListener.java
  src/main/java/com/gdschongik/gdsc/domain/discord/dto/response/DiscordNicknameResponse.java
  src/main/java/com/gdschongik/gdsc/domain/member/api/OnboardingMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/AdminMemberResponse.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberBasicInfoResponse.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberInfoResponse.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/dto/response/AdminRecruitmentResponse.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/dto/response/AdminRecruitmentRoundResponse.java
  src/main/java/com/gdschongik/gdsc/global/common/constant/DiscordConstant.java
  src/main/java/com/gdschongik/gdsc/global/config/DiscordConfig.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
  src/main/java/com/gdschongik/gdsc/global/util/formatter/MoneyFormatter.java
  src/main/java/com/gdschongik/gdsc/global/util/formatter/PhoneFormatter.java
  src/main/java/com/gdschongik/gdsc/global/util/formatter/SemesterFormatter.java
Labels: ♻️ refactor

#496 hotfix: 스웨거 CORS URL 등록
  src/main/java/com/gdschongik/gdsc/global/config/WebSecurityConfig.java
Labels: 🐛 bug/error

#505 test: 리쿠르팅 테스트 상수 이름 수정
  src/test/java/com/gdschongik/gdsc/domain/member/application/AdminMemberServiceTest.java
  src/test/java/com/gdschongik/gdsc/domain/membership/domain/MembershipTest.java
  src/test/java/com/gdschongik/gdsc/domain/membership/domain/MembershipValidatorTest.java
  src/test/java/com/gdschongik/gdsc/domain/order/application/OrderServiceTest.java
  src/test/java/com/gdschongik/gdsc/domain/order/domain/OrderValidatorTest.java
  src/test/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentServiceTest.java
  src/test/java/com/gdschongik/gdsc/domain/recruitment/domain/RecruitmentRoundValidatorTest.java
  src/test/java/com/gdschongik/gdsc/global/common/constant/RecruitmentConstant.java
  src/test/java/com/gdschongik/gdsc/helper/IntegrationTest.java
Labels: ✅ test

#503 refactor: 준회원으로 일괄 강등 로직에 도메인 서비스 적용
  src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/MemberValidator.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentService.java
  src/test/java/com/gdschongik/gdsc/domain/member/application/AdminMemberServiceTest.java
  src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberValidatorTest.java
Labels: ♻️ refactor

#517 refactor: 검증 메서드 로직 단순화
  src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/vo/Period.java
  src/main/java/com/gdschongik/gdsc/global/security/CustomSuccessHandler.java
Labels: ♻️ refactor

#515 test: 템플릿에 역할별 멤버 생성 메서드 추가
  src/test/java/com/gdschongik/gdsc/helper/FixtureHelper.java
  src/test/java/com/gdschongik/gdsc/helper/IntegrationTest.java
Labels: ✅ test

#527 fix: PaymentFeignClient 설정 중복 제거
  src/main/java/com/gdschongik/gdsc/infra/feign/payment/config/PaymentClientConfig.java
Labels: 🐛 bug/error

#523 feat: 신청 가능한 스터디 조회 API 추가
  src/main/java/com/gdschongik/gdsc/domain/study/api/StudyController.java
  src/main/java/com/gdschongik/gdsc/domain/study/application/StudyService.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/Study.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyType.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/request/StudyCreateRequest.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/StudyResponse.java
  src/test/java/com/gdschongik/gdsc/domain/order/application/OrderServiceTest.java
Labels: ✨ feature

#532 feat: 스터디 수강신청 API 추가
  src/main/java/com/gdschongik/gdsc/domain/study/api/StudyController.java
  src/main/java/com/gdschongik/gdsc/domain/study/application/StudyService.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/StudyHistoryRepository.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/Study.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyHistory.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyHistoryValidator.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
  src/test/java/com/gdschongik/gdsc/domain/study/application/StudyServiceTest.java
  src/test/java/com/gdschongik/gdsc/domain/study/domain/StudyHistoryValidatorTest.java
  src/test/java/com/gdschongik/gdsc/helper/FixtureHelper.java
Labels: ✨ feature

#513 refactor: 인증시 학교 이메일 인증 메일 전송 여부 판단 로직 추가
  build.gradle
  src/main/java/com/gdschongik/gdsc/domain/discord/application/listener/PingpongListener.java
  src/main/java/com/gdschongik/gdsc/domain/email/application/UnivEmailVerificationLinkSendService.java
  src/main/java/com/gdschongik/gdsc/domain/email/application/UnivEmailVerificationService.java
  src/main/java/com/gdschongik/gdsc/domain/email/dao/UnivEmailVerificationRepository.java
  src/main/java/com/gdschongik/gdsc/domain/email/domain/EmailVerificationStatusService.java
  src/main/java/com/gdschongik/gdsc/domain/email/domain/UnivEmailValidator.java
  src/main/java/com/gdschongik/gdsc/domain/email/domain/UnivEmailVerification.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/OnboardingMemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/AssociateRequirement.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/MemberFullDto.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/UnivVerificationStatus.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberDashboardResponse.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
  src/test/java/com/gdschongik/gdsc/config/TestRedisConfig.java
  src/test/java/com/gdschongik/gdsc/domain/email/application/UnivEmailVerificationServiceTest.java
  src/test/java/com/gdschongik/gdsc/domain/email/domain/UnivEmailValidatorTest.java
  src/test/java/com/gdschongik/gdsc/global/common/constant/MemberConstant.java
  src/test/resources/application-test.yml
Labels: ♻️ refactor

#536 feat: 스터디 수강신청 취소 API 추가
  src/main/java/com/gdschongik/gdsc/domain/study/api/StudyController.java
  src/main/java/com/gdschongik/gdsc/domain/study/application/StudyService.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/StudyHistoryRepository.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyHistoryValidator.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
  src/test/java/com/gdschongik/gdsc/domain/study/domain/StudyHistoryValidatorTest.java
Labels: ✨ feature
