Repository gdg-hongik-univ/gdsc-server, pull requests merged in 2024-09, with the labels that each got.

#733 feat: 커리큘럼 응답에 상태 필드 추가
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/StudyCurriculumResponse.java
Labels: ✨ feature

#743 feat: 깃허브 레포지토리 정규표현식 추가
  src/main/java/com/gdschongik/gdsc/domain/study/dto/request/RepositoryUpdateRequest.java
  src/main/java/com/gdschongik/gdsc/global/common/constant/RegexConstant.java
Labels: ✨ feature

#746 refactor: 주차별 출결 번호 이번주차와 다음주차만 뜨도록 변경
  src/main/java/com/gdschongik/gdsc/domain/study/application/MentorStudyDetailService.java
Labels: ♻️ refactor

#750 fix: 레포지토리 조회 메서드가 레포지토리 링크를 받도록 수정
  src/main/java/com/gdschongik/gdsc/domain/study/application/StudentStudyHistoryService.java
  src/main/java/com/gdschongik/gdsc/infra/github/client/GithubClient.java
Labels: 🐛 bug/error

#748 refactor: 멤버십 unique constraint 추가
  src/main/java/com/gdschongik/gdsc/domain/membership/domain/Membership.java
Labels: ♻️ refactor

#762 feat: 제출 가능한 과제 API 응답에 최종 수정 일시 필드 추가
  src/main/java/com/gdschongik/gdsc/domain/study/api/StudentStudyDetailController.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/AssignmentSubmittableDto.java
Labels: ✨ feature

#768 fix: 스터디 공지 조회 API 역할 검증 로직 제거
  src/main/java/com/gdschongik/gdsc/domain/study/application/CommonStudyService.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyValidator.java
  src/test/java/com/gdschongik/gdsc/domain/study/domain/StudyValidatorTest.java
Labels: 🐛 bug/error

#770 refactor: 테스트에서만 사용하는 메서드 제거
  src/main/java/com/gdschongik/gdsc/domain/membership/application/MembershipService.java
  src/main/java/com/gdschongik/gdsc/domain/membership/domain/Membership.java
  src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
Labels: ✅ test, ♻️ refactor

#771 test: 학년도와 학기 상수 분리
  src/test/java/com/gdschongik/gdsc/domain/member/domain/MemberValidatorTest.java
  src/test/java/com/gdschongik/gdsc/domain/membership/application/MembershipServiceTest.java
  src/test/java/com/gdschongik/gdsc/domain/membership/domain/MembershipTest.java
  src/test/java/com/gdschongik/gdsc/domain/membership/domain/MembershipValidatorTest.java
  src/test/java/com/gdschongik/gdsc/domain/order/application/OrderServiceTest.java
  src/test/java/com/gdschongik/gdsc/domain/recruitment/application/AdminRecruitmentServiceTest.java
  src/test/java/com/gdschongik/gdsc/domain/recruitment/domain/RecruitmentRoundValidatorTest.java
  src/test/java/com/gdschongik/gdsc/domain/recruitment/domain/RecruitmentTest.java
  src/test/java/com/gdschongik/gdsc/domain/study/application/AdminStudyServiceTest.java
  src/test/java/com/gdschongik/gdsc/domain/study/domain/StudyTest.java
  src/test/java/com/gdschongik/gdsc/global/common/constant/RecruitmentConstant.java
  src/test/java/com/gdschongik/gdsc/global/common/constant/SemesterConstant.java
  src/test/java/com/gdschongik/gdsc/global/common/constant/TemporalConstant.java
  src/test/java/com/gdschongik/gdsc/helper/FixtureHelper.java
  src/test/java/com/gdschongik/gdsc/helper/IntegrationTest.java
Labels: ✅ test

#772 refactor: enum equals 로직 개선
  src/main/java/com/gdschongik/gdsc/domain/discord/domain/DiscordValidator.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/MemberStatus.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/RecruitmentRound.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/RecruitmentRoundValidator.java
  src/main/java/com/gdschongik/gdsc/domain/recruitment/domain/RoundType.java
Labels: ♻️ refactor

#773 refactor: 출석체크시 수강신청 여부 검증 로직을 도메인 서비스로 이동
  src/main/java/com/gdschongik/gdsc/domain/study/application/StudentStudyService.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/AttendanceValidator.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
  src/test/java/com/gdschongik/gdsc/domain/study/domain/AttendanceValidatorTest.java
Labels: ♻️ refactor

#782 feat: 스터디 수료 필드와 우수 스터디원 테이블 추가
  src/main/java/com/gdschongik/gdsc/domain/study/domain/AchievementType.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyAchievement.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyHistory.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyHistoryStatus.java
  src/test/java/com/gdschongik/gdsc/domain/study/domain/StudyHistoryTest.java
Labels: ✨ feature
