Repository gdg-hongik-univ/gdsc-server, pull requests merged in 2024-08, with the labels that each got.

#543 feat: 과제 조회 API 추가
  src/main/java/com/gdschongik/gdsc/domain/study/api/StudyMentorController.java
  src/main/java/com/gdschongik/gdsc/domain/study/application/StudyMentorService.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/StudyDetailRepository.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/AssignmentResponse.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
Labels: ✨ feature

#542 feat: 과제 휴강 처리 API 추가
  src/main/java/com/gdschongik/gdsc/domain/study/api/StudyMentorController.java
  src/main/java/com/gdschongik/gdsc/domain/study/application/StudyMentorService.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyDetail.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyDetailValidator.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/vo/Assignment.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
  src/test/java/com/gdschongik/gdsc/domain/study/application/StudyMentorServiceTest.java
  src/test/java/com/gdschongik/gdsc/domain/study/domain/StudyDetailTest.java
  src/test/java/com/gdschongik/gdsc/domain/study/domain/StudyDetailValidatorTest.java
  src/test/java/com/gdschongik/gdsc/global/common/constant/StudyConstant.java
  src/test/java/com/gdschongik/gdsc/helper/FixtureHelper.java
  src/test/java/com/gdschongik/gdsc/helper/IntegrationTest.java
Labels: ✨ feature

#573 fix: PrincipalDetails가 역할의 값을 반환하도록 수정
  src/main/java/com/gdschongik/gdsc/global/security/PrincipalDetails.java
Labels: 🐛 bug/error

#574 refactor: 멘토 컨트롤러 엔드포인트 정리
  src/main/java/com/gdschongik/gdsc/domain/study/api/MentorStudyDetailController.java
  src/main/java/com/gdschongik/gdsc/domain/study/application/MentorStudyDetailService.java
  src/main/java/com/gdschongik/gdsc/global/config/WebSecurityConfig.java
  src/test/java/com/gdschongik/gdsc/domain/study/application/MentorStudyDetailServiceTest.java
Labels: ♻️ refactor

#570 feat: 과제 히스토리 테이블 추가
  src/main/java/com/gdschongik/gdsc/domain/study/domain/AssignmentHistory.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/AssignmentSubmissionStatus.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/SubmissionFailureType.java
Labels: ✨ feature

#613 feat: 내 담당 스터디 목록 조회 API 추가
  src/main/java/com/gdschongik/gdsc/domain/study/api/MentorStudyController.java
  src/main/java/com/gdschongik/gdsc/domain/study/application/MentorStudyService.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/StudyRepository.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/MentorStudyResponse.java
Labels: ✨ feature

#632 refactor: 스터디 개설시 제목필드 추가
  src/main/java/com/gdschongik/gdsc/domain/study/domain/Study.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/request/StudyCreateRequest.java
  src/main/java/com/gdschongik/gdsc/domain/study/factory/StudyDomainFactory.java
  src/test/java/com/gdschongik/gdsc/domain/study/domain/StudyTest.java
  src/test/java/com/gdschongik/gdsc/global/common/constant/StudyConstant.java
  src/test/java/com/gdschongik/gdsc/helper/FixtureHelper.java
  src/test/java/com/gdschongik/gdsc/helper/IntegrationTest.java
Labels: ✨ feature

#635 feat: 과제 제출하기 1차 로직 구현
  src/main/java/com/gdschongik/gdsc/domain/study/application/StudentStudyHistoryService.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/AssignmentHistoryRepository.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/StudyHistoryRepository.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/AssignmentHistory.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyAssignmentHistoryValidator.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyDetail.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/vo/Assignment.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
  src/test/java/com/gdschongik/gdsc/domain/study/domain/StudyAssignmentHistoryValidatorTest.java
  src/test/java/com/gdschongik/gdsc/global/common/constant/StudyConstant.java
  src/test/java/com/gdschongik/gdsc/helper/FixtureHelper.java
Labels: ✨ feature

#575 feat: 제출 가능한 과제 조회 API 추가
  src/main/java/com/gdschongik/gdsc/domain/study/api/StudentStudyController.java
  src/main/java/com/gdschongik/gdsc/domain/study/api/StudentStudyDetailController.java
  src/main/java/com/gdschongik/gdsc/domain/study/application/StudentStudyDetailService.java
  src/main/java/com/gdschongik/gdsc/domain/study/application/StudentStudyService.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/StudyHistoryRepository.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/AssignmentHistory.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyDetail.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/vo/Assignment.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/AssignmentDashboardResponse.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/AssignmentResponse.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/AssignmentSubmittableDto.java
  src/test/java/com/gdschongik/gdsc/domain/study/application/StudentStudyServiceTest.java
Labels: ✨ feature

#623 feat: 스터디 수강생 명단 조회
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
  src/main/java/com/gdschongik/gdsc/domain/study/api/MentorStudyController.java
  src/main/java/com/gdschongik/gdsc/domain/study/application/MentorStudyService.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/StudyHistoryRepository.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/Study.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyValidator.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/StudyStudentResponse.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
  src/test/java/com/gdschongik/gdsc/domain/study/domain/StudyValidatorTest.java
  src/test/java/com/gdschongik/gdsc/helper/FixtureHelper.java
Labels: ✨ feature

#641 feat: 스터디 공지 생성,수정,삭제 API 추가
  src/main/java/com/gdschongik/gdsc/domain/study/api/MentorStudyController.java
  src/main/java/com/gdschongik/gdsc/domain/study/api/StudentStudyController.java
  src/main/java/com/gdschongik/gdsc/domain/study/application/MentorStudyService.java
  src/main/java/com/gdschongik/gdsc/domain/study/application/StudentStudyService.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/StudyAnnouncementRepository.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/StudyRepository.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyAnnouncement.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/request/StudyAnnouncementCreateUpdateRequest.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/request/StudyAttendCreateRequest.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
Labels: ✨ feature

#651 fix: objectMapper에 JavaTimeModule 추가
  src/main/java/com/gdschongik/gdsc/global/config/ObjectMapperConfig.java
Labels: 🐛 bug/error

#654 feat: StudyResponse에 학년도와 학기 추가
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/StudyResponse.java
Labels: ✨ feature

#644 feat: 스터디 공지 목록 조회 API 추가
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
  src/main/java/com/gdschongik/gdsc/domain/study/api/CommonStudyController.java
  src/main/java/com/gdschongik/gdsc/domain/study/application/CommonStudyService.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/StudyAnnouncementRepository.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyValidator.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/StudyAnnouncementResponse.java
  src/test/java/com/gdschongik/gdsc/domain/study/domain/StudyValidatorTest.java
Labels: ✨ feature

#652 feat: 신청 가능한 스터디 조회 API에 이미 신청한 스터디 ID 필드 추가
  src/main/java/com/gdschongik/gdsc/domain/study/api/StudentStudyController.java
  src/main/java/com/gdschongik/gdsc/domain/study/application/StudentStudyService.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/StudyApplicableResponse.java
Labels: ✨ feature

#658 fix: Time관련 필드 Deserializer 맵퍼에 추가
  src/main/java/com/gdschongik/gdsc/global/config/ObjectMapperConfig.java
Labels: 🐛 bug/error

#660 feat: 스터디 종료 시간과 신청 종료일 추가
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/StudyResponse.java
Labels: ✨ feature

#662 feat: 수강생 스터디 커리큘럼 조회 API 추가
  src/main/java/com/gdschongik/gdsc/domain/study/api/StudentStudyDetailController.java
  src/main/java/com/gdschongik/gdsc/domain/study/application/MentorStudyDetailService.java
  src/main/java/com/gdschongik/gdsc/domain/study/application/MentorStudyService.java
  src/main/java/com/gdschongik/gdsc/domain/study/application/StudentStudyDetailService.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/AttendanceCustomRepository.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/AttendanceCustomRepositoryImpl.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/AttendanceRepository.java
  src/main/java/com/gdschongik/gdsc/domain/study/dao/StudyDetailRepository.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/AssignmentHistory.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/AssignmentSubmissionStatus.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/vo/Assignment.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/AssignmentSubmissionStatusResponse.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/AttendanceStatusResponse.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/StudyStudentSessionResponse.java
  src/test/java/com/gdschongik/gdsc/domain/study/application/MentorStudyServiceTest.java
Labels: ✨ feature

#676 fix: dev 스웨거 cors에러 해결
  src/main/java/com/gdschongik/gdsc/global/config/WebSecurityConfig.java
Labels: 🐛 bug/error

#678 refactor: 과제 매핑 정보 수정
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyDetail.java
Labels: ♻️ refactor

#672 feat: 마이페이지 계정정보 조회 API 추가
  src/main/java/com/gdschongik/gdsc/domain/member/api/CommonMemberController.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/CommonMemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/dto/response/MemberAccountInfoResponse.java
  src/main/java/com/gdschongik/gdsc/global/common/constant/GithubConstant.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
  src/main/java/com/gdschongik/gdsc/infra/github/GithubUserRequest.java
  src/main/java/com/gdschongik/gdsc/infra/github/client/GithubClient.java
Labels: ✨ feature

#671 feat: 내 할일 목록 조회 API 추가
  src/main/java/com/gdschongik/gdsc/domain/study/api/StudentStudyDetailController.java
  src/main/java/com/gdschongik/gdsc/domain/study/application/StudentStudyDetailService.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyDetail.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/vo/Session.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/StudyTodoResponse.java
Labels: ✨ feature

#681 feat: 스터디 기초 난이도 추가 및 세션조회에 과제제출링크 필드 추가
  src/main/java/com/gdschongik/gdsc/domain/study/domain/Difficulty.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/StudyStudentSessionResponse.java
Labels: ✨ feature

#688 feat: 스터디 주차별 출결번호 조회
  src/main/java/com/gdschongik/gdsc/domain/study/api/MentorStudyDetailController.java
  src/main/java/com/gdschongik/gdsc/domain/study/application/MentorStudyDetailService.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyDetail.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/StudyMentorAttendanceResponse.java
Labels: ✨ feature

#692 feat: 어드민에게 멘토 API 접근 권한 부여
  src/main/java/com/gdschongik/gdsc/global/config/WebSecurityConfig.java
Labels: ✨ feature

#694 refactor: 스터디 개강일 전에도 내 수강중인 스터디 조회 API에서 선별할 수 있도록 수정
  src/main/java/com/gdschongik/gdsc/domain/study/application/StudentStudyService.java
Labels: ♻️ refactor

#712 feat: 멘토 권한 부여 로직 추가
  src/main/java/com/gdschongik/gdsc/domain/study/application/AdminStudyService.java
  src/test/java/com/gdschongik/gdsc/domain/study/application/AdminStudyServiceTest.java
Labels: ✨ feature

#704 fix: ZonedDateTime ObjectMapper가 인식하도록 수정
  src/main/java/com/gdschongik/gdsc/domain/order/dao/OrderQueryMethod.java
  src/main/java/com/gdschongik/gdsc/global/common/constant/RegexConstant.java
  src/main/java/com/gdschongik/gdsc/global/config/ObjectMapperConfig.java
Labels: 🐛 bug/error

#719 refactor: 대시보드 response에 feeName 필드 추가
  src/main/java/com/gdschongik/gdsc/domain/recruitment/dto/RecruitmentRoundFullDto.java
Labels: ♻️ refactor

#721 fix: 과제 미제출과 제출전을 구별하도록 수정
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/AssignmentHistoryStatusResponse.java
  src/main/java/com/gdschongik/gdsc/domain/study/dto/response/AssignmentSubmittableDto.java
Labels: 🐛 bug/error

#710 fix: 스터디 중복신청 불가능하도록 수정
  src/main/java/com/gdschongik/gdsc/domain/study/application/StudentStudyService.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/Study.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyHistory.java
  src/main/java/com/gdschongik/gdsc/domain/study/domain/StudyHistoryValidator.java
Labels: 🐛 bug/error
