Repository gdg-hongik-univ/gdsc-server, pull requests merged in 2025-04, with the labels that each got.

#1017 chore: CloudWatch 이용 로그 수집
  docker-compose.yml
  src/main/java/com/gdschongik/gdsc/global/common/constant/UrlConstant.java
  src/main/java/com/gdschongik/gdsc/global/log/LoggingFilter.java
  src/main/resources/application-local.yml
  src/main/resources/logback-spring.xml
Labels: ⚙️ chore

#1019 feat: 어드민 권한 부여 디스코드 커맨드 구현
  src/main/java/com/gdschongik/gdsc/domain/discord/application/handler/AssignAdminRoleCommandHandler.java
  src/main/java/com/gdschongik/gdsc/domain/discord/application/listener/AssignAdminRoleCommandListener.java
  src/main/java/com/gdschongik/gdsc/domain/member/application/AdminMemberService.java
  src/main/java/com/gdschongik/gdsc/domain/member/dao/MemberRepository.java
  src/main/java/com/gdschongik/gdsc/domain/member/domain/Member.java
  src/main/java/com/gdschongik/gdsc/global/common/constant/DiscordConstant.java
  src/main/java/com/gdschongik/gdsc/global/config/DiscordConfig.java
Labels: ✨ feature

#1023 feat: 수강신청 철회시 출석 및 과제 이력 삭제
  src/main/java/com/gdschongik/gdsc/domain/studyv2/application/CommonStudyServiceV2.java
  src/main/java/com/gdschongik/gdsc/domain/studyv2/application/handler/StudyEventHandlerV2.java
  src/main/java/com/gdschongik/gdsc/domain/studyv2/domain/StudyApplyCanceledEvent.java
  src/main/java/com/gdschongik/gdsc/domain/studyv2/domain/StudyHistoryV2.java
Labels: ✨ feature

#1025 feat: 누락된 스터디 역할 부여 케이스 처리를 위한 디스코드 커맨드
  src/main/java/com/gdschongik/gdsc/domain/discord/application/CommonDiscordService.java
  src/main/java/com/gdschongik/gdsc/domain/discord/application/handler/AssignStudyRoleCommandHandler.java
  src/main/java/com/gdschongik/gdsc/domain/discord/application/listener/AssignStudyRoleCommandListener.java
  src/main/java/com/gdschongik/gdsc/domain/studyv2/dao/StudyV2Repository.java
  src/main/java/com/gdschongik/gdsc/global/common/constant/DiscordConstant.java
  src/main/java/com/gdschongik/gdsc/global/config/DiscordConfig.java
Labels: ✨ feature

#1070 refactor: 출석 기한 검증 에러 코드 네이밍 변경
  src/main/java/com/gdschongik/gdsc/domain/study/domain/service/AttendanceValidator.java
  src/main/java/com/gdschongik/gdsc/domain/studyv2/domain/service/AttendanceValidatorV2.java
  src/main/java/com/gdschongik/gdsc/global/exception/ErrorCode.java
  src/test/java/com/gdschongik/gdsc/domain/study/domain/AttendanceValidatorTest.java
Labels: ♻️ refactor
